name: frontend-ci

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: frontend-ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node 20 and pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm manually
        run: npm install -g pnpm@9

      - name: Confirm pnpm is available
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

      - name: Run unit tests (Vitest)
        run: pnpm run test -- --run

      - name: Build production bundle (Vite)
        run: pnpm run build
